use_frameworks!

target 'WriteWorkLib_Example' do
  pod 'WriteWorkLib', :path => '../WriteWorkLib.podspec'

  target 'WriteWorkLib_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
